name: Mirror Repo
on:
  push:
    # Run on push, mainly for rapid testing
  watch:
    # Run if someone stars the repo!
    types: [started]
  schedule:
    # 4 times a day
    - cron:  "42 */8 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner
    steps:
    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< '${{ secrets.SSH_PRIVATE_KEY }}'
        git config --global user.email "eschwartz@cert.org"
        git config --global user.name "sei-eschwartz"
    - name: Merge master
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        git clone 'git@github.com:sei-eschwartz/pharos.git'
        cd pharos
        git remote add upstream https://github.com/cmu-sei/pharos.git
        git fetch upstream
        git merge upstream/master
        git push
